name: "ret2z's blog"
description: "ret2z的个人技术博客"

avatar: https://zhzflhs.github.io/images/avatar.png
favicon: https://zhzflhs.github.io/images/favicon.ico

navigation:
  - name: 首页
    url: /
  - name: 关于
    url: /about
  - name: 分类
    url: /tags

paginate: 8

excerpt_separator: <!-- more -->

footer-links:
  zhihu: 
  email: xiongyunhan@outlook.com
  facebook:
  github: zhzflhs
  rss: welcome!
  twitter: 
  youtube:

footer-text: Copyright (c) 2024-2025 ret2z

url: https://zhzflhs.github.io

permalink: /:title/
paginate_path: /page:num/

# Gitalk
gitalk:
  clientID: cba98a0db83eb062c0f8
  clientSecret: 46400b2614fb5c4189f6c5f662baee088712b316
  repo: zhzflhs.github.io
  owner: ret2z

# The release of Jekyll Now
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

